FI17/Befragungstool

Umfrage-Tool/.vs/config/applicationhost.config
Umfrage-Tool/Umfrage-Tool/Views/Shared/_Layout.cshtml

Title changed

---

Umfrage-Tool/Umfrage-Tool/Views/Home/Index.cshtml

Button "Umfrage erstellen" zu Html.ActionLink gewandelt, damit er dynamisch an die richtige Stelle leitet

Bugfix: Button "Umfrage erstellen" 

---

Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/Index.cshtml

größtenteils an Vorlage orientiert
Der Link zum View der Frageerstellung muss über Postmethode der Index-Action des Umfrage_ErstellenControllers erfolgen

Umfrage_Erstellen Index angepasst

---

Umfrage-Tool/Umfrage-Tool/FromModelTransformer/Answering/ModelToAnsweringTransformer.cs
Umfrage-Tool/Umfrage-Tool/FromModelTransformer/Answers/ModelToAnswerTransformer.cs
Umfrage-Tool/Umfrage-Tool/FromModelTransformer/Question/ModelToQuestionTransformer.cs
Umfrage-Tool/Umfrage-Tool/FromModelTransformer/Session/ModelToSessionTransformer.cs
Umfrage-Tool/Umfrage-Tool/FromModelTransformer/Survey/ModelToSurveyTransformer.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Answer/AnswerToModelTransformer.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Answering/AnsweringToModelAllTransformer.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Answering/AnsweringToModelTransformer.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Question/QuestionToModelTransformer.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Session/SessionToModelTransformer.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Survey/SurveyToModelQuestionTransformer.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Survey/SurveyToModelSessionTransformer.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Survey/SurveyToModelTransformer.cs

LIstTransformer

---

Umfrage-Tool/Umfrage-Tool/Controllers/Umfrage_ErstellungController.cs
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/FrageErstellung.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/Plus_Antwort.cshtml

Frageerstellung speichert Text, Typ und Antwortmoeglichkeiten

---

Umfrage-Tool/Umfrage-Tool/Controllers/Umfrage_ErgebnisseController.cs
Umfrage-Tool/Umfrage-Tool/Controllers/Umfrage_ErstellungController.cs
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Beantwortung/MultipleOne.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Beantwortung/Skalenfrage.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Ergebnisse/Fragen_Ergebnisse.cshtml
Umfrage-Tool/Umfrage-Tool/Web.config

Beantwortung: Skalenfragen und MultipleOne überarbeitet
Auswertung: kumulierte Auswertung

Grobe Überarbeitung vom master

---

Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Ergebnisse/Fragen_Ergebnisse.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/Plus_Antwort.cshtml

JS entfernt in Fragen Ergebnisse

---

Umfrage-Tool/Umfrage-Tool/Content/Auswertung.css
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Ergebnisse/Skalenfrage_Kumuliert.cshtml

Wurde an neues Skalenfragenkonzept angepasst
Co-Authored-By: traeumerle <traeumerle@users.noreply.github.com>

Kumulierte Skalenfragen-Auswertung

---

Umfrage-Tool/Umfrage-Tool/Controllers/Umfrage_ErgebnisseController.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Answering/AnsweringToModelSessionTransformer.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Question/QuestionToModelTransformer.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Session/SessionToModelSurveyTransformer.cs
Umfrage-Tool/Umfrage-Tool/Umfrage-Tool.csproj
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Ergebnisse/MultipleMoreMitSonstiges_Kumuliert.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Ergebnisse/MultipleMore_Kumuliert.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Ergebnisse/Panel_fuer_Frage_in_kumulierter_Auswertung.cshtml
Umfrage-Tool/Umfrage-Tool/Web.config

Co-Authored-By: traeumerle <traeumerle@users.noreply.github.com>

Anzahl auswertung hinzugefügt

---

Umfrage-Tool/Umfrage-Tool/Controllers/HomeController.cs
Umfrage-Tool/Umfrage-Tool/Umfrage-Tool.csproj
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Admin.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Normaler_Nutzer.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Index.cshtml

Erstellte Umfragen-Tabelle in Partial-VIEWs aufgeteilt und Admin-Tabelle

---

Umfrage-Tool/Umfrage-Tool/Scripts/Frageerstellung.js
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/Multiple_Choice_Fragen_Erstellung.cshtml

Es gibt nur noch 15 Antwortmöglichkeiten in der Erstellung

---

Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Beantwortung/Umfrage_beendet.cshtml

"Umfrage beendet"-Glückwünschung wurde überarbeitet

---

Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Ergebnisse/Fragen_Ergebnisse.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Ergebnisse/Panel_fuer_Frage_in_kumulierter_Auswertung.cshtml

Anzahl wird OBEN angeziegt und Tab-Titel ist jetzt der Umfragename

---

Umfrage-Tool/Umfrage-Tool/Controllers/AccountController.cs
Umfrage-Tool/Umfrage-Tool/Controllers/HomeController.cs
Umfrage-Tool/Umfrage-Tool/Views/Home/Index.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Shared/_Layout.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Shared/_LoginPartial.cshtml
Umfrage-Tool/Umfrage-Tool/Web.config
Umfrage-Tool/Umfrage-Tool/database.cs

Registrierseite Hinzugefügt

---

Umfrage-Tool/Umfrage-Tool/Scripts/Abfrage_vorm_löschen.js
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Admin.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Normaler_Nutzer.cshtml
Umfrage-Tool/Umfrage-Tool/Web.config

in admin-view und normaler-view

link in zwischenablage kopieren

---

Umfrage-Tool/Umfrage-Tool/Controllers/AccountController.cs

Rollenzuweisung in der Registrierung hinzugefügt.

Ungetested

---

Umfrage-Tool/Umfrage-Tool/Controllers/AccountController.cs

Änderungen ungetestet

---

Umfrage-Tool/Umfrage-Tool/Scripts/Abfrage_vorm_löschen.js
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Admin.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Normaler_Nutzer.cshtml

Veröffentlichen und Beenden erfordern nun estätigung

Umfrage Veröffentlichen und Umfrage beenden funktionnieren

---

Umfrage-Tool/Umfrage-Tool/Controllers/Umfrage_ErstellungController.cs
Umfrage-Tool/Umfrage-Tool/Scripts/Frageerstellung.js
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/FrageErstellung.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/Multiple_Choice_Fragen_Erstellung.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/Skalenfragen_Erstellung.cshtml

Fragen werden "leer" gespeichert

---

Umfrage-Tool/Umfrage-Tool/Controllers/AccountController.cs

Registrierung ist nurnoch mit Adminrechten möglich.

Registrierung mit Adminrechten

---

Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/FrageErstellung.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/MultipleMore.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/MultipleMoreMitSonstiges.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/MultipleOne.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/MultipleOneMitSonstiges.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/Skalenfrage.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/Vorschau.cshtml

Textfeldern in Bearbeitung das required-Attribut hinzugefügt und Textlänge begrenzt

3 Bugfixes in der Bearbeitung

---

Umfrage-Tool/Umfrage-Tool/Views/Account/Login.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Account/NutzerHinzugefügt.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Fehlermeldungen/AuswertungKeineAntworten.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Fehlermeldungen/StatusUmfrageAuswertung.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Fehlermeldungen/StatusUmfrageBeantwortung.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Fehlermeldungen/StatusUmfrageBearbeitung.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Index.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Beantwortung/Umfrage_beendet.cshtml

veränderte Dateien:
- Home
- Nutzer hinzugefügt
- Umfrage beendet
- StatusUmfrageBearbeitung
- StatusUmfrageBeantwortung
- StatusUmfrageAuswertung
- AuswertungKeineAntworten

Fehler- und Erfolgsseiten an CD angepasst und Debug-Knöpfe in Home-VIEW

---

Umfrage-Tool/Umfrage-Tool/Controllers/Umfrage_BeantwortungController.cs

Sessions werden beim Fertigstellen erstellt

---

Umfrage-Tool/Domain/Survey.cs
Umfrage-Tool/Umfrage-Tool/Controllers/HomeController.cs
Umfrage-Tool/Umfrage-Tool/Controllers/Umfrage_ErstellungController.cs
Umfrage-Tool/Umfrage-Tool/FromModelTransformer/Survey/ModelToSurveyTransformer.cs
Umfrage-Tool/Umfrage-Tool/Models/SurveyViewModel.cs
Umfrage-Tool/Umfrage-Tool/Scripts/Abfrage_vorm_löschen.js
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Survey/SurveyToModelQuestionTransformer.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Survey/SurveyToModelSessionTransformer.cs
Umfrage-Tool/Umfrage-Tool/ToModelTransformer/Survey/SurveyToModelTransformer.cs
Umfrage-Tool/Umfrage-Tool/Umfrage-Tool.csproj
Umfrage-Tool/Umfrage-Tool/Views/Home/Index.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Umfrage_freigeben.cshtml

Datenbank, Transformer und ViewModels angepasst
Neuer View um Enddatum festzulegen
keine Abfrage im Home-View, ob Umfrage veröffentlicht werden soll, weil man eh auf die Freigabe-View geleitet wird, wo es einen Abbrechen-Knopf gibt

Freigabe-Funktion implementiert

---

Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/MultipleMore.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/MultipleMoreMitSonstiges.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/MultipleOne.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/MultipleOneMitSonstiges.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/Vorschau.cshtml

Stundenlang dran gesessen für 1 Wort pro Button hinzufügen :disappointed:

Löschen funktioniert bei leeren Buttons

---

Umfrage-Tool/Umfrage-Tool/Controllers/Umfrage_ErstellungController.cs
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/Skalenfragen_Erstellung.cshtml

Skalen werden Autotomatisch beschrifftet

---

Umfrage-Tool/Umfrage-Tool/Content/Home.css
Umfrage-Tool/Umfrage-Tool/Scripts/Home_View Seitenumbruch.js
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Admin.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Normaler_Nutzer.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Index.cshtml
Umfrage-Tool/Umfrage-Tool/database.cs

Es erscheinen Pfeile neben dem Spaltentitel

---

Umfrage-Tool/Umfrage-Tool/Scripts/Popover.js
Umfrage-Tool/Umfrage-Tool/Umfrage-Tool.csproj
Umfrage-Tool/Umfrage-Tool/Views/Account/Login.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Account/Register.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Admin.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Normaler_Nutzer.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Index.cshtml

- Popover für die Home-Views
- Popover für die Anmeldung
- Popover für die Registrierung

Popover Kapitel

---

Umfrage-Tool/Umfrage-Tool/Controllers/AccountController.cs
Umfrage-Tool/Umfrage-Tool/Controllers/Auswertung_EinzelController.cs
Umfrage-Tool/Umfrage-Tool/Controllers/Auswertung_kumuliertController.cs
Umfrage-Tool/Umfrage-Tool/Controllers/FehlermeldungenController.cs
Umfrage-Tool/Umfrage-Tool/Controllers/HomeController.cs
Umfrage-Tool/Umfrage-Tool/Controllers/Umfrage_BeantwortungController.cs
Umfrage-Tool/Umfrage-Tool/Controllers/Umfrage_ErstellungController.cs
Umfrage-Tool/Umfrage-Tool/Models/Message.cs
Umfrage-Tool/Umfrage-Tool/Umfrage-Tool.csproj
Umfrage-Tool/Umfrage-Tool/Views/Fehlermeldungen/FehlerMeldung.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Admin.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Index.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Umfrage_Erstellung/Vorschau.cshtml

Dateien wurden wieder eingefügt

---

Umfrage-Tool/Umfrage-Tool/Scripts/Abfrage_vorm_löschen.js
Umfrage-Tool/Umfrage-Tool/Scripts/Home_View Seitenumbruch.js
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Admin.cshtml

- Bei Ersteller ändern ist ein Bug aufgetreten, weil JEMAND einen Variablennamen nicht an ALLEN Stellen angepasst hat
- Wenn eine Spalte nur den gleichen Inhalt hat, konnte nicht sortiert werden. Jetzt werden die Zeilen komplett umgedreht.

2 Bugfixes

---

Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Admin.cshtml
Umfrage-Tool/Umfrage-Tool/Views/Home/Erstellte_Umfragen_Normaler_Nutzer.cshtml

Die Status erhalten hier ein Bootstrap Glyphicons zur visuellen Unterscheidung

Status mit Icons

---

Umfrage-Tool/Umfrage-Tool/Views/Auswertung_Einzel/Antworten.cshtml

Co-Authored-By: Nils Rücker <nilsrucker@users.noreply.github.com>

Bugfix eintzelauswertung
